### ISSUE TITLE
Cluster addon CRDs are not installed

### ISSUE THREAD

**Issue by chess-knight** [SovereignCloudStack/cluster-stack-operator#130]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Install cluster addon with CRDs

**Comment by guettli** [comment]
@chess-knight can you please provide an example where this fails? I am a bit confused that it worked for us up to now. I guess CRDs are only considered CRDs for helm, if they are in the directory `crd`. Maybe our add-ons don't put CRDs into that directory.

**Comment by chess-knight** [comment]
> @chess-knight can you please provide an example where this fails? I am a bit confused that it worked for us up to now. I guess CRDs are only considered CRDs for helm, if they are in the directory `crd`. Maybe our add-ons don't put CRDs into that directory.

Hi @guettli, You are right, the only cluster addon you have in tests is metrics-server. Metrics-server doesn't have `crds` folder, see https://github.com/kubernetes-sigs/metrics-server/tree/master/charts/metrics-server.
But, now I need to install [yawol](https://github.com/stackitcloud/yawol/tree/main/charts/yawol-controller) chart which does have `crds` folder.
