### ISSUE TITLE
support aliases for objects

### ISSUE THREAD

**Issue by kranurag7** [SovereignCloudStack/cluster-stack-operator#152]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

We as of now don't have any aliases for our types (clusterstack, clusterstackrelease and clusteraddon) as of now. This issue is a discussion where we can agree on having a common alias and use the same going forward with kubectl, k9s etc. 

We have these three types as of now. 

```bash
clusterstack.x-k8s.io                      ClusterAddon                              v1alpha1        Namespaced        18m 
clusterstack.x-k8s.io                      ClusterStackRelease                       v1alpha1        Namespaced        18m 
clusterstack.x-k8s.io                      ClusterStack                              v1alpha1        Namespaced        18m 
```

From my end, I am proposing the following aliases: 
`csk` for clusterstack
`cskr` for clusterstackrelease
`caddons` for clusteraddons

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This is an open discussion. 

// cc @janiskemper @guettli @michal-gubricky @chess-knight @matofeder

**Comment by guettli** [comment]
looks good. But I would use `caddon`.

**Comment by janiskemper** [comment]
I prefer "cs" for clusterstack. Why do you say "csk"?

**Comment by chess-knight** [comment]
> I prefer "cs" for clusterstack. Why do you say "csk"?

```bash
$ kubectl get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS    MESSAGE   ERROR
controller-manager   Healthy   ok        
scheduler            Healthy   ok        
etcd-0               Healthy   ok
```

**Comment by chess-knight** [comment]
CAPI has "cl" for the Cluster, so maybe `cls` and `clsr`?

**Comment by kranurag7** [comment]
> CAPI has "cl" for the Cluster, so maybe `cls` and `clsr`?

I'll prefer this over `csk` and `cskr` I hope these are not conflicting with any widely used OSS project.

**Comment by kranurag7** [comment]
We can use GitHub search to find conflicting names. 

`csk`: no conflicts (ref: https://github.com/search?q=%22shortName%3Dcsk%22+&type=code) 
`cls`: clusternet project uses it (ref: https://github.com/search?q=%22shortName%3Dcls%22+&type=code)

**Comment by chess-knight** [comment]
> We can use GitHub search to find conflicting names.
> 
> `csk`: no conflicts (ref: https://github.com/search?q=%22shortName%3Dcsk%22+&type=code)
> `cls`: clusternet project uses it (ref: https://github.com/search?q=%22shortName%3Dcls%22+&type=code)

Then, `csk` looks good to me
