### ISSUE TITLE
Delete failed to evaluate CEL condition on success

### ISSUE THREAD

**Issue by aniruddha2000** [SovereignCloudStack/cluster-stack-operator#214]
/kind bug

**What steps did you take and what happened:**
right now we don't delete failed to evaluate CEL condition on success, we should delete it

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-stack-operator version:
- Kubernetes version: (use `kubectl version`)
- OS (e.g. from `/etc/os-release`):

**Comment by janiskemper** [comment]
duplicate of #198
