### ISSUE TITLE
Update to CAPI 1.8

### ISSUE THREAD

**Issue by janiskemper** [SovereignCloudStack/cluster-stack-operator#251]
/kind feature

**Describe the solution you'd like**
Update to CAPI 1.8 and bump all related dependencies.

**Comment by guettli** [comment]
This means we need to update controller-runtime. I suggest aligning with capi and use version 0.19.

Unfortunately we use controller-runtime 0.17.x at the moment. Version 0.18 introduced typed (generic) functions, and the transition is not trivial.

Related: https://kubernetes.slack.com/archives/C02MRBMN00Z/p1713976216050739

I am working on it.
