### ISSUE TITLE
BeforeClusterUpgrade hook blocks Cluster upgrades

### ISSUE THREAD

**Issue by chess-knight** [SovereignCloudStack/cluster-stack-operator#259]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I upgraded the cluster by changing the `topology.class` and `topology.version` fields in the Cluster object.
Cluster API is not starting the upgrade process, instead, I see in the CAPI logs:
```
Calling all extensions of hook "BeforeClusterUpgrade"
Calling extension handler "before-cluster-upgrade.cso-hook-server-extensionconfig"
extension handler returned blocking response with retryAfterSeconds of 10
Cluster upgrade to version "v1.28.13" is blocked by "BeforeClusterUpgrade" hook
```
and CSO logs:
```
"file":"extension/hooks.go:56","message":"DoBeforeClusterUpgrade is called"
```

**What did you expect to happen:**
Successful upgrade of the cluster.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I do not use multi-stage addons.
ClusterAddon CR is READY and inside `.spec` has already upgraded `clusterStack` and `version` fields.
Also, caddon is missing `HelmChartApplied` in `.status.conditions`.

**Environment:**

- cluster-stack-operator version: v0.1.0-alpha.7
- Kubernetes version: v1.30.0
- OS (e.g. from `/etc/os-release`):

**Comment by janiskemper** [comment]
I think that the controller takes the cluster stack assets as base for the decision whether there are multi-stage cluster addons or not. Apparently, it thought here, that there are. I think there might be something with your folder structure of the clusteraddon/ folder or the clusteraddon.yaml

**Comment by chess-knight** [comment]
> I think that the controller takes the cluster stack assets as base for the decision whether there are multi-stage cluster addons or not. Apparently, it thought here, that there are. I think there might be something with your folder structure of the clusteraddon/ folder or the clusteraddon.yaml

I am using https://github.com/chess-knight/cluster-stacks/releases/tag/openstack-scs-1-28-v2 release and trying to upgrade on https://github.com/chess-knight/cluster-stacks/releases/tag/openstack-scs-1-28-v3. These releases are based on https://github.com/SovereignCloudStack/cluster-stacks/tree/release-1.28/providers/openstack/scs structure. So IMO these are not multi-stage cluster-addons.
I created them by the following:
```
csctl create providers/openstack/scs/ -m custom --cluster-stack-version v2 --cluster-addon-version v2 --node-image-version v1
csctl create providers/openstack/scs/ -m custom --cluster-stack-version v3 --cluster-addon-version v3 --node-image-version v2
```

**Comment by janiskemper** [comment]
tbh I also don't see the reason right now. Did you find the place in the code where it is decided whether we follow the multi stage way or not? I don't see right now why it takes the wrong decision in your case

**Comment by chess-knight** [comment]
> tbh I also don't see the reason right now. Did you find the place in the code where it is decided whether we follow the multi stage way or not? I don't see right now why it takes the wrong decision in your case

I can see that the BeforeClusterUpgrade hook https://github.com/SovereignCloudStack/cluster-stack-operator/blob/v0.1.0-alpha.7/extension/hooks.go#L54 is called also for legacy cluster addons. And I see that something removes `"HelmChartApplied"` condition and that's why it fails. But I don't know if it is the hook itself or the caddon controller.

**Comment by janiskemper** [comment]
sorry, I was on the wrong track here.. The hooks are of course always called! The question of multi-stage or not is irrelevant for the hooks. That's just a question on how many Helm charts there are and what format they have.

**Comment by chess-knight** [comment]
> sorry, I was on the wrong track here.. The hooks are of course always called! The question of multi-stage or not is irrelevant for the hooks. That's just a question on how many Helm charts there are and what format they have.

Yeah, there is one helm chart with 5 dependencies. But all of them are successfully applied to the workload cluster.

**Comment by janiskemper** [comment]
so it works or it doesn't work?

**Comment by chess-knight** [comment]
As I said, the upgrade of k8s is blocked by `BeforeClusterUpgrade` hook.

**Comment by janiskemper** [comment]
so how does the ClusterAddon object look like? The status should show what's going on.. Or events, logs, etc.

**Comment by chess-knight** [comment]
This is strange, I cannot reproduce it.
