### ISSUE TITLE
Replace sub-command execution with proper code for Helm

### ISSUE THREAD

**Issue by NotTheEvilOne** [SovereignCloudStack/cluster-stack-operator#33]
Reviewing the current operator I found `helmTemplate`which calls the `helm` executable to render the chart template.

https://github.com/SovereignCloudStack/cluster-stack-operator/blob/ad039ca93ea62c13a504d09b753c9b00e3ab3be8/internal/controller/clusterstackrelease_controller.go#L312

I would consider this function bad practice that needs replacement as soon as possible because of at least the following reasons:
- Running an executable without any additional checks of unknown source even thought you _think_ it's provided by the Dockerfile during the build process is an security issue
- Downloading a binary for a single task seems bloated additionally
- Each executable in a file system might be an unnecessary attack vector on containers.
- KISS principle

There are at least two libraries (Helm [1] and go-helm-client [2]) that would just add the dependencies required to get the job done. 

[1] https://github.com/helm/helm
[2] https://github.com/mittwald/go-helm-client

**Comment by janiskemper** [comment]
We followed the approach of ArgoCD (see e.g. https://github.com/argoproj/argo-cd/blob/820f4d861a7789f299143ed89816001091abf923/util/helm/cmd.go#L54).

If there is an easier way, I'm open to other approaches! If you want to contribute, I can also support you on this.

**Comment by jschoone** [comment]
I would close for now. The issue can be reopened together with the PR if needed.
