### ISSUE TITLE
Helm template, how to feed values

### ISSUE THREAD

**Issue by mxmxchere** [SovereignCloudStack/cluster-stack-operator#37]
How does one supply helm-values to the helm-charts? If i understand the code here correctly it only renders the template with its default values.

https://github.com/SovereignCloudStack/cluster-stack-operator/blob/4c4f9061cd6b59887241a81631a115bdde12624b/internal/controller/clusterstackrelease_controller.go#L312

**Comment by janiskemper** [comment]
I have asked the experts to answer. However, your question is about how to write Helm charts. The operator does not allow any Helm values to be specified by the user. 

So either you should re-phrase this question in how to build cluster stacks (and it should be in the cluster-stacks repo), or this is a question about the operator and then the answer would be that it is not possible to specify helm values as a user.

**Comment by mxmxchere** [comment]
> The operator does not allow any Helm values to be specified by the user.

Ok, what is the benefit to use helm over static manifests then?

**Comment by mxmxchere** [comment]
yes, thank you very much for explaining.
