### ISSUE TITLE
Create GitHub client only if it is necessary

### ISSUE THREAD

**Issue by chess-knight** [SovereignCloudStack/cluster-stack-operator#58]
/kind feature

Do not create github client when it is not needed.

**Describe the solution you'd like**

1. clusterstackrelease controller creates github client even when it is not needed:
   - see https://github.com/SovereignCloudStack/cluster-stack-operator/blob/main/internal/controller/clusterstackrelease_controller.go#L99
   - it is used only when `download` is `true` https://github.com/SovereignCloudStack/cluster-stack-operator/blob/main/internal/controller/clusterstackrelease_controller.go#L130
2. clusterstack controller creates github client even when it is not needed:
   - see https://github.com/SovereignCloudStack/cluster-stack-operator/blob/main/internal/controller/clusterstack_controller.go#L112
   - it is used only when `clusterStack.Spec.AutoSubscribe` is `true` https://github.com/SovereignCloudStack/cluster-stack-operator/blob/main/internal/controller/clusterstack_controller.go#L542

**Comment by kranurag7** [comment]
Hey, regarding 2nd, I think we need one in the main Reconcile method. 

https://github.com/SovereignCloudStack/cluster-stack-operator/blob/adb648ceaebddca04a015fbea0319110ca99a5cc/internal/controller/clusterstack_controller.go#L126

FYI, I'm not considering where we change the function signature of `getLatestReleaseFromRemoteRepository` but as of now this function expects a GitHub client and we create that in the main Reconcile method.

**Comment by janiskemper** [comment]
you can move the check for Autosubscribe outside of this utility function, so that the function is never called if autosubscribe is not true. Then you can create the client only when needed
